<?php $this->layout('layout::home-usuario'); ?>
<?php $this->headTitle('Editar Usuario'); ?>
<?php $form = $this->form; ?>
<?php $form->prepare(); ?>

<?php
$partes = explode(' ', $this->form->get('nome')->getValue());
$primeiroNome = array_shift($partes);
$ultimoNome = array_pop($partes);
$nome_usuario = $primeiroNome . ' ' . $ultimoNome;
?>

<?= $this->form()->openTag($form) ?>

<div class="w-full max-w-full bg-white shadow-md rounded-lg mt-18">

    <?php if ($this->message): ?>
        <div class="min-w-full mt-0 mb-2">
            <span class="text-[#ce0808]"><?= $this->escapeHtml($this->message) ?></span>
        </div>
    <?php endif; ?>

    <div class="p-3 max-w-180 mx-auto">
        <div class="w-full text-xl mb-2">
            <span class="w-full text-blue-600 flex justify-center hyphens-none">Editar cadastro: <?= $nome_usuario ?></span>
        </div>
        <div class="w-full">
            <a href="javascript:history.go(-1)" class="text-blue-700 text-base flex justify-end">
                <span class="material-icons-regular text-sm">Arrow_Back</span>
                voltar
            </a>
        </div>
    </div>

    <div class="flex flex-wrap rounded-md gap-4 p-2 text-sm max-w-200 mx-auto mt-0">
        <div class="flex-1 w-full min-w-50 block">
            <span class="block text-gray-500 whitespace-nowrap"><?= $this->formLabel($form->get('nome')) ?></span>
            <?= $this->formElement($form->get('nome')) ?>
            <p id="erro-nome" class="hidden mt-1 text-xs text-red-600 font-semibold">⚠️ Informe o seu nome ou Razão social</p>
            <span class="text-[#ce0808]"> <?= $this->formElementErrors($form->get('nome')) ?></span>
        </div>

        <div class="flex-1 w-full min-w-50">
            <span class="block text-gray-500 whitespace-nowrap"><?= $this->formLabel($form->get('documento')) ?></span>
            <?= $this->formElement($form->get('documento')) ?>
            <p id="erro-documento" class="hidden mt-1 text-xs text-red-600 font-semibold">⚠️ Este não é um número de CPF ou CNPJ</p>
            <p id="erro-docVazio" class="hidden mt-1 text-xs text-red-600 font-semibold">⚠️ informe o seu CPF ou CNPJ</p>
            <span class="text-[#ce0808]"> <?= $this->formElementErrors($form->get('documento')) ?></span>
        </div>

        <div class="flex-1 w-full min-w-50">
            <span class="block text-gray-500 whitespace-nowrap"><?= $this->formLabel($form->get('telefone')) ?></span>
            <?= $this->formElement($form->get('telefone')) ?>
            <p id="erro-telefone" class="hidden mt-1 text-xs text-red-600 font-semibold">⚠️ Este número não é de um Celular ou Telefone</p>
            <p id="erro-foneVazio" class="hidden mt-1 text-xs text-red-600 font-semibold">⚠️ informe seu Celular ou telefone, com DDD</p>
            <span class="text-[#ce0808]"> <?= $this->formElementErrors($form->get('telefone')) ?></span>
        </div>


        <div class="flex-1 w-full min-w-50">
            <span class="block text-gray-500 whitespace-nowrap"><?= $this->formLabel($form->get('email')) ?></span>
            <?= $this->formElement($form->get('email')) ?>
            <p id="erro-emailVazio" class="hidden mt-1 text-xs text-red-600 font-semibold">⚠️ informe seu E-mail</p>
            <span class="text-[#ce0808]"> <?= $this->formElementErrors($form->get('email')) ?></span>
        </div>


        <div class="flex-1 w-full min-w-50">
            <span class="block text-gray-500 whitespace-nowrap"><?= $this->formLabel($form->get('cep')) ?></span>
            <?= $this->formElement($form->get('cep')) ?>
            <p id="erro-CEP" class="hidden mt-1 text-xs text-red-600 font-semibold">⚠️ Formato de CEP: 00000-000</p>
            <p id="erro-cepVazio" class="hidden mt-1 text-xs text-red-600 font-semibold">⚠️ informe o seu CEP</p>
            <p id="erro-cepNaoEnc" class="hidden mt-1 text-xs text-red-600 font-semibold">⚠️ O CEP informado não foi encontrado</p>
            <span class="text-[#ce0808]"> <?= $this->formElementErrors($form->get('cep')) ?></span>
        </div>

        <div class="flex-1 w-full min-w-50">
            <span class="block text-gray-500 whitespace-nowrap"><?= $this->formLabel($form->get('uf')) ?></span>
            <?= $this->formElement($form->get('uf')) ?>
            <p id="erro-ufVazio" class="hidden mt-1 text-xs text-red-600 font-semibold">⚠️ informe a Sigla do seu Estado</p>
            <span class="text-[#ce0808]"> <?= $this->formElementErrors($form->get('uf')) ?></span>
        </div>

        <div class="flex-1 w-full min-w-50">
            <span class="block text-gray-500 whitespace-nowrap"><?= $this->formLabel($form->get('localidade')) ?></span>
            <?= $this->formElement($form->get('localidade')) ?>
            <p id="erro-localVazio" class="hidden mt-1 text-xs text-red-600 font-semibold">⚠️ informe a sua Cidade</p>
            <span class="text-[#ce0808]"> <?= $this->formElementErrors($form->get('localidade')) ?></span>
        </div>

        <div class="flex-1 w-full min-w-50">
            <span class="block text-gray-500 whitespace-nowrap"><?= $this->formLabel($form->get('bairro')) ?></span>
            <?= $this->formElement($form->get('bairro')) ?>
            <p id="erro-bairroVazio" class="hidden mt-1 text-xs text-red-600 font-semibold">⚠️ informe o seu Bairro</p>
            <span class="text-[#ce0808]"> <?= $this->formElementErrors($form->get('bairro')) ?></span>
        </div>

        <div class="flex-1 w-full min-w-50">
            <span class="block text-gray-500 whitespace-nowrap"><?= $this->formLabel($form->get('logradouro')) ?></span>
            <?= $this->formElement($form->get('logradouro')) ?>
            <p id="erro-logrVazio" class="hidden mt-1 text-xs text-red-600 font-semibold">⚠️ informe o seu Logradouro</p>
            <span class="text-[#ce0808]"> <?= $this->formElementErrors($form->get('logradouro')) ?></span>
        </div>

        <div class="flex-1 w-full min-w-50">
            <span class="block text-gray-500 whitespace-nowrap"><?= $this->formLabel($form->get('complementos')) ?></span>
            <?= $this->formElement($form->get('complementos')) ?>
            <p id="erro-complementos" class="hidden mt-1 text-xs text-red-600 font-semibold">⚠️ informe os Complementos do seu endereço</p>
            <span class="text-[#ce0808]"> <?= $this->formElementErrors($form->get('complementos')) ?></span>
        </div>

        <?php if ($this->user_role === 'admin'): ?>
            <div class="flex-1 w-full min-w-50">
                <span class="block text-gray-500 whitespace-nowrap"><?= $this->formLabel($form->get('role')) ?></span>
                <?= $this->formElement($form->get('role')) ?>
                <span class="text-[#ce0808]"> <?= $this->formElementErrors($form->get('role')) ?></span>
            </div>
        <?php endif; ?>
        <div class="flex justify-center flex-wrap rounded-md gap-4 p-2 text-sm w-full mx-auto mt-0">
            <div class="flex-1 min-w-50 max-w-50">
                <!-- Botões de Cancelar/Enviar -->
                <a href="javascript:history.go(-1)">
                    <div class="w-full min-w-50 p-0.5 cursor-pointer bg-blue-600 hover:bg-blue-700 text-white rounded-md transition flex items-center justify-center disabled:bg-blue-400">
                        <span>Cancelar e voltar</span>
                    </div>
                </a>
            </div>
            <div class="flex-1 max-w-50">
                <button type="submit" id="btnEnviar" class="min-w-50 max-w-50 p-0.5 cursor-pointer bg-blue-600 hover:bg-blue-700 text-white   rounded-md transition flex items-center justify-center disabled:bg-blue-400">
                    <svg id="spinner" class="animate-spin -ml-1 mr-3 h-5 w-5 text-white hidden" xmlns="http://www.w3.org" fill="none" viewBox="0 0 24 24">
                        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                    <span id="textoBotao">Salvar alterações</span>
                </button>
            </div>
        </div>
    </div>
</div>

<?= $this->form()->closeTag() ?>

</div>
</div>
<script type="text/javascript" src="/js/editarUsuario.js"></script>