<?php $this->layout('layout::home-usuario'); ?>

<?php
/** @var array $aula */
/** @var iterable $monitores */
/**  @var iterable $atletas */
/**  @var string $datas */
?>

<div class="container mx-auto p-3 bg-white shadow-lg rounded-lg mt-3">
    <h1 class="text-xl text-blue-600 mb-6 border-b pb-2">
        Editando a aula de <?= $this->escapeHtml($aula['data']); ?>
    </h1>

    <form method="POST" class="space-y-6">

        <!-- CABEÇALHO DA AULA (Editável) -->
        <div class="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-6 gap-4 bg-gray-50  rounded-md">
            <div>
                <label class="block text-sm text-gray-600">Nível</label>
                <input type="text" name="nivel" value="<?= $this->escapeHtml($aula['nivel']) ?>" maxlength="20" readonly placeholder="formato 00:00hs" class="border border-gray-300 rounded-md px-4 py-2 w-full focus:outline-none focus:ring-1 focus:ring-blue-300 focus:border-blue-500">
            </div>
            <div>
                <label class="block text-sm text-gray-600">Local</label>
                <input type="text" name="local" value="<?= $this->escapeHtml($aula['local']) ?>" maxlength="20" placeholder="cidade" class="border border-gray-300 rounded-md px-4 py-2 w-full focus:outline-none focus:ring-1 focus:ring-blue-300 focus:border-blue-500">
            </div>
            <div>
                <label class="block text-sm text-gray-600">Dia</label>
                <input type="text" name="dia" value="<?= $this->escapeHtml($aula['dia']) ?>" maxlength="20" placeholder="dia da semana" class="border border-gray-300 rounded-md px-4 py-2 w-full focus:outline-none focus:ring-1 focus:ring-blue-300 focus:border-blue-500">
            </div>
            <div>
                <label class="block text-sm text-gray-600">Início</label>
                <input type="text" name="inicio" value="<?= $aula['inicio_formatado'] ?>" maxlength="7" placeholder="formato 00:00hs" class="border border-gray-300 rounded-md px-4 py-2 w-full focus:outline-none focus:ring-1 focus:ring-blue-300 focus:border-blue-500">
            </div>
            <div>
                <label class="block text-sm text-gray-600">Término</label>
                <input type="text" name="termino" value="<?= $aula['termino_formatado'] ?>" maxlength="7" placeholder="formato 00:00hs" class="border border-gray-300 rounded-md px-4 py-2 w-full focus:outline-none focus:ring-1 focus:ring-blue-300 focus:border-blue-500">
            </div>
            <div>
                <label class="block text-sm text-gray-600">Data</label>
                <input type="text" name="data" id="data" value="<?= $aula['data'] ?>" maxlength="10" placeholder="formato 00:00hs" class="border border-gray-300 rounded-md px-4 py-2 w-full focus:outline-none focus:ring-1 focus:ring-blue-300 focus:border-blue-500">
            </div>
        </div>

        <!-- MONITORES -->
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <datalist id="lista-monitor1">
                <?php foreach ($this->monitores as $monitor): ?>
                    <option value="<?= $this->escapeHtml($monitor) ?>">
                    <?php endforeach; ?>
            </datalist>
            <div>
                <label class="block text-sm text-gray-700">Monitor 1</label>
                <input type="text" name="monitor1" list="lista-monitor1" id="monitor1" maxlength="50" class="w-full&#x20;indent-1&#x20;border&#x20;rounded&#x20;border-gray-300&#x20;focus&#x3A;bg-gray-100&#x20;outline-none&#x20;focus&#x3A;border-blue-500" placeholder="Escolha um nome da lista ou digite o nome do novo monitor" value="<?= $aula['monitor1'] ?>">
            </div>
            <datalist id="lista-monitor2">
                <?php foreach ($this->monitores as $monitor): ?>
                    <option value="<?= $this->escapeHtml($monitor) ?>">
                    <?php endforeach; ?>
            </datalist>
            <div>
                <label class="block text-sm text-gray-700">Monitor 2</label>
                <input type="text" name="monitor2" list="lista-monitor2" id="monitor2" maxlength="50" class="w-full&#x20;indent-1&#x20;border&#x20;rounded&#x20;border-gray-300&#x20;focus&#x3A;bg-gray-100&#x20;outline-none&#x20;focus&#x3A;border-blue-500" placeholder="Escolha um nome da lista ou digite o nome do novo monitor" value="<?= $aula['monitor2'] ?>">
            </div>
        </div>

        <!-- TABELA DE ATLETAS -->
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div class="overflow-x-auto border rounded-lg">
                <table class="w-full text-left">
                    <thead class="bg-blue-600 text-white text-base">
                        <tr>
                            <th class="text-center font-normal">Presença</th>
                            <th class="text-center font-normal">Nome do Atleta</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y">

                        <?php $presentes = explode(',', $aula['presentes']); ?>
                        <?php $presentes = array_map('trim', $presentes); ?>
                        <?php foreach ($presentes as $atleta): ?>
                            <?php $atleta = htmlspecialchars($atleta); ?>
                            <tr class="hover:bg-blue-50 transition-colors">
                                <td class="text-center">
                                    <!-- Checkbox: Marcado envia o nome para o array no POST -->
                                    <input type="checkbox" name="atletas_presentes[]"
                                        value="<?= $atleta ?>"
                                        class="w-5 h-5 accent-blue-600" checked>
                                </td>
                                <td class="p-3 font-medium text-gray-700"><?= $atleta ?></td>
                            </tr>
                        <?php endforeach; ?>

                        <?php $ausentes = explode(',', $aula['ausentes']); ?>
                        <?php $ausentes = array_map('trim', $ausentes); ?>
                        <?php foreach ($ausentes as $atleta): ?>
                            <?php $atleta = htmlspecialchars($atleta); ?>
                            <?php if ($atleta !== ''): ?>
                                <tr class="hover:bg-blue-50 transition-colors">
                                    <td class="p-3 text-center">
                                        <!-- Checkbox: Marcado envia o nome para o array no POST -->
                                        <input type="checkbox" name="atletas_presentes[]"
                                            value="<?= $atleta ?>"
                                            class="w-5 h-5 accent-blue-600" />
                                    </td>
                                    <td class="p-3 font-medium text-gray-700"><?= $atleta ?></td>
                                </tr>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>

            <!-- ANOTAÇÕES -->
            <div>
                <label class="block text-sm text-gray-600 mb-1">Notas da Aula</label>
                <textarea name="nota" rows="3" class="w-full p-2 border border-gray-300 rounded-md field-sizing-content" placeholder="Ex.: Aluno X machucou o joelho, avisar responsáveis..."><?= $aula['nota'] ?></textarea>
            </div>
        </div>

        <!-- BOTÕES -->
        <div class="flex justify-end space-x-4">
            <a href="/aulas" class="px-6 py-2 border rounded text-gray-600 hover:bg-gray-300">Cancelar</a>
            <button type="submit" class="px-6 py-2 cursor-pointer bg-green-600 text-white rounded hover:bg-green-700 shadow-md">
                Editar Aula
            </button>
        </div>
    </form>
</div>