<!-- src/App/templates/app/forgot-password.phtml -->

<?php $this->layout('layout::home-usuario'); ?>



<div class="mt-10 flex items-center justify-center">
   
    <div class="max-w-md p-2 bg-white rounded-lg shadow-md border border-gray-200 text-sm">
                <?php if (!empty($message)): ?>
            <div class="max-w-100 m-auto mb-5 text-blue-800 text-sm"><?= $message ?></div>
            <hr /><br />
        <?php endif; ?>
        
        <h2 class="text-2xl  text-center text-gray-800 mb-6">Recupere sua senha</h2>
        <span class="text-sm text-center block px-4 hyphens-none">Digite seu e-mail cadastrado na Axel Patinação para receber o link de redefinição</span><br />

        <form method="post" action="">

            <div class="mb-4">
                <label for="email" class="block text-sm  text-gray-600 mb-1">Seu e-mail cadastrado conosco</label>
                <input type="email" name="email" id="email" required class="w-full p-2 border rounded focus:ring-2 focus:ring-blue-500 outline-none border-gray-300">
            </div>

             <button type="submit" class="mt-2 p-1 text-sm cursor-pointer w-full bg-blue-500 hover:bg-blue-700 text-white font-semi-bold rounded transition">Enviar Link de Recuperação</button>
        </form>

    </div>
</div>