<?php $this->layout('layout::home-usuario'); ?>


<div class="mt-10 flex items-center justify-center">
    <div class="max-w-md p-2 bg-white rounded-lg shadow-md border border-gray-200">
        
        <h2 class="text-2xl  text-center text-gray-800 mb-6">Verifique seu E-mail</h2>
        <span class="text-sm text-center block px-4 hyphens-none">
            <p>Você receberá um link de confirmação em instantes. Clique nele ou copie e cole no seu navegador para acessar a página de confirmação.</p>
            <p>O link expira em 1 hora. Não esqueça de checar a pasta de <strong>Spam</strong>.</p>
        </span><br />


    </div>
</div>