<!-- src/App/templates/app/forgot-password.phtml -->

<?php $this->layout('layout::home-usuario'); ?>

<div class="mt-20 flex items-center justify-center  text-gray-600">

    <div class="max-w-md m-4 p-2 bg-white rounded-lg shadow-md border border-gray-200 text-sm">
        <?php if (!empty($message)): ?>
            <div class="max-w-100 m-auto mb-5 text-blue-800 text-sm"><?= $message ?></div>
            <hr /><br />
        <?php endif; ?>

        <h2 class="text-2xl  text-center text-gray-500">Recupere sua senha</h2>
        <span class="text-base text-center block px-4 mt-5 hyphens-none">Digite seu e-mail cadastrado na Axel Patinação para receber o link de redefinição</span>

        <form method="post" class="p-6" action="">
  <label for="email" class="block text-sm  text-gray-600 mb-1">Seu e-mail cadastrado conosco</label>
            <div class="mb-4">
                <div class="relative w-full max-w-sm">
                    
                    <!-- Ícone de Envelope -->
                    <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                        <svg xmlns="http://w3.org" class="h-5 w-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                        </svg>
                    </div>
                    
                    <!-- Input -->
                <input type="email" name="email" id="email" required class="w-full p-0.5 border rounded-md focus:ring-2 focus:ring-blue-500 outline-none border-gray-300 pl-10">
                </div>

            </div>

            <button type="submit" class="mt-2 p-0.5 text-sm cursor-pointer w-full bg-blue-500 hover:bg-blue-700 text-white font-semi-bold rounded-md transition">Enviar Link de Recuperação</button>
        </form>

    </div>
</div>