<?php $this->layout('layout::home-usuario'); ?>
<?php $urlCompleta = $_SERVER['REQUEST_URI'];
$url = parse_url($urlCompleta, PHP_URL_QUERY); ?>

<?php if (isset($mensagensSucesso)): $this->message = $this->escapeHtml($mensagensSucesso);
endif;
$partes = explode(' ', $usuarios[0]['nome']);
$primeiroNome = array_shift($partes);
$ultimoNome = array_pop($partes);
$nome_usuario = $primeiroNome . ' ' . $ultimoNome;
?>

<div class="flex-wrap mt-20 justify">
    <div class="flex flex-1 min-w-25 justify-center">
        <h1 class="text-xl sm:text-[22px] max-w-full text-blue-600">Perfil do usuário - <?= $nome_usuario ?> </h1>
    </div>
    <div class="flex-1 min-w-25 max-w-250 text-center flex justify-end text-blue-600 mr-auto">
        <a href="javascript:history.go(-1)">
            <span class="material-icons-regular text-sm">
                Arrow_Back
            </span>
            voltar
        </a>
    </div>
</div>
<?php if (count($this->usuarios) > 0): ?>

    <main class="w-full mx-auto pb-10 lg:py-6 lg:px-8 lg:grid lg:grid-cols-12 lg:gap-x-5">
            <nav class="lg:col-span-3 pb-4">
                <div class="max-w-70">
                    <a href="/editar_usuario/<?= $usuarios[0]['id'] ?>" title="Editar o perfil do usuário" class="max-w-40">
                        <li class="rounded-md hover:bg-slate-200 gap-4 p-1 max-w-90 flex float:left items-center">
                            <span class="material-icons-regular mr-10 text-[30px] text-[#a15959]">Manage_Accounts</span>
                            Editar perfil de:<br>
                            <?= $nome_usuario ?>
                        </li>
                    </a>
                </div>
                <?php if ($usuarios[0]['role'] === 'titular'): ?>
                    <div class="max-w-40">
                        <a href="/novo_atleta" title="Registrar um atleta">
                            <li class="rounded-md hover:bg-slate-200 indent-3 mt-6 w-50 flex float:left items-center">
                                <span class="material-icons-regular text-[19px] text-[#a15959]">face</span>
                                Novo Atleta
                            </li>
                        </a>
                    </div>
                    <div class="max-w-40"> 
                        <?php $n = urlencode($usuarios[0]['nome']); ?>
                        <a href="<?= $this->url('atletas.listar', ['titular' => $n]) ?>" title="Listar os atletas do titular">
                            <li class="rounded-md hover:bg-slate-200 indent-3 mt-2 w-50 flex float:left items-center">
                                <span class="material-icons-regular text-[19px] text-[#a15959]">face</span>
                                Atletas
                            </li>
                        </a>
                    </div>
                    <div class="max-w-40"><a href="https://axelpatinacao.basedeclientes.com.br" target="_blank" title="Área financeira da Axel">
                            <li class="rounded-md hover:bg-slate-200 indent-3 mt-2 w-50 flex float:left items-center"><span class="material-icons-regular text-[19px] text-[#a15959]">Attach_Money</span> Financeiro</li>
                        </a>
                    </div>
                    <!--
                    <div class="max-w-full">
                        <button id="botaoAbrir" onclick="carregar()" class="hidden cursor-point m-4 bg-indigo-200 hover:bg-indigo-400 text-black px-6 py-2 rounded-full font-medium transition-all cursor-pointer">
                            Financeiro
                        </button>
                        <div id="modalFrame" class="relative overflow-hidden h-20">
                            <div id="loader" class="hidden absolute inset-0 flex-col items-center justify-center bg-white z-10">
                                <div class="animate-spin rounded-full h-10 w-10 border border-indigo-200 border-t-indigo-600"></div>
                                <p class="mt-2 text-sm text-gray-500 font-medium">Carregando...</p>
                            </div>
                            <div id="containerConteudo" class="bg-white w-3/4 h-3/4 relative rounded shadow-xl hidden">
                                <iframe id="meuFrame" src="about:blank" class="max-w-full h-screen border-none"></iframe>
                            </div>
                        </div>
                    </div> 
                -->
                    <?php endif; ?>
            </nav>
        <div class="space-y-1 lg:px-0 lg:col-span-8 w-full">
                <?php if (isset($this->message)): ?>
                    <div class="col-span-12 mb-6">
                        <div rows="3" class="field-sizing-content mt-1 block w-full border border-blue-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-primary focus:border-primary sm:text-sm text-blue-700">
                            <?= $this->escapeHtml($this->message) ?>
                        </div>
                    </div>
                <?php endif; ?>
                <div>
                    <h2 class="mt-1 block w-full border-gray-300 shadow-sm px-2 pt-0.5 text-base bg-blue-200 rounded-md sm:text-lg font-normal text-gray-900">PERFIL DE USUÁRIO</h2>
                </div>
                <div class="flex flex-wrap bg-gray-50 rounded-md gap-3 p-3 space-y-4 text-base w-full">
                    <div class="flex-1 w-full min-w-50"><label class="block text-sm font-medium text-gray-600">Nome:</label> <span class="whitespace-nowrap mt-1 block w-full border-b border-gray-300 shadow-sm px-2 text-base"><?= $usuarios[0]['nome'] ?></span></div>
                    <div class="flex-1 w-full min-w-50"><label class="block text-sm font-medium text-gray-900">E-mail:</label> <span class="mt-1 block w-full border-b border-gray-300 shadow-sm px-2 text-base"><?= $usuarios[0]['email'] ?></span></div>
                    <div class="flex-1 w-full min-w-50"><label class="block text-sm font-medium text-gray-900">Documento:</label> <span class="mt-1 block w-full border-b border-gray-300 shadow-sm px-2 text-sm"><?= strlen($usuarios[0]['documento']) === 11 ? vsprintf('%s%s%s.%s%s%s.%s%s%s-%s%s', str_split($usuarios[0]['documento'])) : vsprintf("%s%s.%s%s%s.%s%s%s/%s%s%s%s-%s%s", str_split($usuarios[0]['documento'])) ?></span></div>
                    <div class="flex-1 w-full min-w-50"><label class="block text-sm font-medium text-gray-900">Fone:</label> <span class="mt-1 block w-full border-b border-gray-300 shadow-sm px-2 text-sm"> <?= strlen($usuarios[0]['telefone']) === 11 ? vsprintf('(%s%s) %s%s%s%s%s-%s%s%s%s', str_split($usuarios[0]['telefone'])) : vsprintf('(%s%s) %s%s%s%s-%s%s%s%s', str_split($usuarios[0]['telefone'])) ?></span></div>
                    <div class="flex-1 w-full min-w-50"><label class="block text-sm font-medium text-gray-900">CEP:</label> <span class="mt-1 block w-full border-b border-gray-300 shadow-sm px-2 text-sm"><?= $usuarios[0]['cep'] ?></span></div>
                    <div class="flex-1 w-full min-w-50"><label class="block text-sm font-medium text-gray-900">Estado:</label> <span class="mt-1 block w-full border-b border-gray-300 shadow-sm px-2 text-base"><?= $usuarios[0]['uf'] ?></span></div>
                    <div class="flex-1 w-full min-w-50"><label class="block text-sm font-medium text-gray-900">Localidade:</label> <span class="mt-1 block w-full border-b border-gray-300 shadow-sm px-2 text-base"><?= $usuarios[0]['localidade'] ?></span></div>
                    <div class="flex-1 w-full min-w-50"><label class="block text-sm font-medium text-gray-900">Bairro:</label> <span class="mt-1 block w-full border-b border-gray-300 shadow-sm px-2 text-base"><?= $usuarios[0]['bairro'] ?></span></div>
                    <div class="flex-1 w-full min-w-50"><label class="block text-sm font-medium text-gray-900">Logradouro:</label> <span class="mt-1 block w-full border-b border-gray-300 shadow-sm px-2 text-base"><?= $usuarios[0]['logradouro'] ?></span></div>
                    <div class="flex-1 w-full min-w-50"><label class="block text-sm font-medium text-gray-900">Complementos:</label> <span class="mt-1 block w-full border-b border-gray-300 shadow-sm px-2 text-base"><?= $usuarios[0]['complementos'] ?></span></div>
                    <div class="flex-1 w-full min-w-50"><label class="block text-sm font-medium text-gray-900">Cadastrado em:</label>
                        <?php $dataUs = $usuarios[0]['data_cadastro'];
                        $date = new DateTime($dataUs);
                        $dataCadastro = $date->format('d-m-Y H:m') . 'hs'; ?>
                        <span class="mt-1 block w-full border-b border-gray-300 shadow-sm px-2 text-sm"><?= $dataCadastro ?> </span>
                    </div>
                </div>
        </div>
    </main>
<?php else: ?>
    <div class="max-w-7xl mx-auto pt-8">
        <h1 class="bg-gray-50 text-xl sm:text-[22px] text-center max-w-full text-blue-600">
            O usuário especificado não consta no nosso sistema
        </h1>

    </div>

<?php endif; ?>