<?php $this->layout('layout::home-usuario'); ?>
<?php
/** @var array $aula */
/** @var iterable $monitores */
/** @var iterable $atletas */
/** @var string $datas */
?>

<div class="mt-16 bg-white shadow-lg rounded-lg overflow-hidden">
    <h1 class="text-xl text-blue-600 mb-2 border-b p-3">
        Exibindo a aula de <?= $this->escapeHtml($aula['data']); ?>
    </h1>
    <div class="p-3 space-y-6">
        <!-- CABEÇALHO DA AULA (Editável) -->
        <div class="flex flex-wrap bg-gray-50 rounded-md gap-3 p-2">
            <div class="flex-1 min-w-25">
                <label class="block text-gray-500 text-xs">Nível</label>
                <div class="border border-gray-300 rounded-md px-2 w-full focus:outline-none focus:ring-1 focus:ring-blue-300 focus:border-blue-500">
                    <?= $this->escapeHtml($aula['nivel']) ?>
                </div>
            </div>
            <div class="flex-1 min-w-25"><label class="block text-gray-500 text-xs">Local</label>
                <div class="border border-gray-300 rounded-md px-2 w-full focus:outline-none focus:ring-1 focus:ring-blue-300 focus:border-blue-500"> <?= $this->escapeHtml($aula['local']) ?> </div>
            </div>
            <div class="flex-1 min-w-25"><label class="block text-gray-500 text-xs">Dia</label>
                <div class="border border-gray-300 rounded-md px-2 w-full focus:outline-none focus:ring-1 focus:ring-blue-300 focus:border-blue-500"><?= $this->escapeHtml($aula['dia']) ?> </div>
            </div>
            <div class="flex-1 min-w-25"><label class="block text-gray-500 text-xs">Início</label>
                <div class="border border-gray-300 rounded-md px-2 w-full focus:outline-none focus:ring-1 focus:ring-blue-300 focus:border-blue-500"><?= $aula['inicio_formatado'] ?> </div>
            </div>
            <div class="flex-1 min-w-25"><label class="block text-gray-500 text-xs">Término</label>
                <div class="border border-gray-300 rounded-md px-2 w-full focus:outline-none focus:ring-1 focus:ring-blue-300 focus:border-blue-500"><?= $aula['termino_formatado'] ?> </div>
            </div>
            <div class="flex-1 min-w-25"><label class="block text-gray-500 text-xs">Data</label>
                <div class="border border-gray-300 rounded-md px-2 w-full focus:outline-none focus:ring-1 focus:ring-blue-300 focus:border-blue-500"><?= $aula['data'] ?> </div>
            </div>
        </div>

        <!-- MONITORES -->
        <div class="flex flex-wrap bg-gray-50 rounded-md gap-3 p-2">
            <div class="flex-1 min-w-25">
                <label class="block text-sm text-gray-700 w-full">
                    Monitor 1
                </label>
                <div class="w-full indent-1 border rounded border-gray-300 focus:bg-gray-100 outline-none focus:border-blue-500">
                    <?= $aula['monitor1'] ?>
                </div>
            </div>
            <?php $monitor2 = $aula['monitor2'] ? $aula['monitor2'] : 'Não houve'; ?>
            <div class="flex-1 min-w-25">
                <label class="block text-sm text-gray-700 w-full">
                    Monitor 2
                </label>
                <div class="w-full indent-1 border rounded border-gray-300 focus:bg-gray-100 outline-none focus:border-blue-500">
                    <?= $monitor2 ?>
                </div>
            </div>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div class="overflow-x-auto border rounded-lg">
                <table class="w-full text-left">
                    <thead class="bg-blue-600 text-white text-base">
                        <tr>
                            <th class="text-center font-normal">Atletas presentes</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y"> <?php $presentes = explode(',', $aula['presentes']); ?> <?php $presentes = array_map('trim', $presentes); ?> <?php foreach ($presentes as $atleta): ?> <?php $atleta = htmlspecialchars($atleta); ?> <tr class="hover:bg-blue-50 transition-colors">
                                <td class="p-3 font-medium text-gray-700"><?= $atleta ?></td>
                            </tr> <?php endforeach; ?> </tbody>
                </table>
            </div>
            <div class="overflow-x-auto border rounded-lg">
                <table class="w-full text-left">
                    <thead class="bg-blue-600 text-white text-base">
                        <tr>
                            <th class="text-center font-normal">Atletas ausentes</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y"> <?php $ausentes = explode(',', $aula['ausentes']); ?> <?php $ausentes = array_map('trim', $ausentes); ?> <?php foreach ($ausentes as $atleta): ?> <?php $atleta = htmlspecialchars($atleta); ?> <?php $atleta = !$atleta ? 'Todos os atletas participaram desta aula' : $atleta; ?> <tr class="hover:bg-blue-50 transition-colors">
                                <td class="p-3 font-medium text-gray-700"><?= $atleta ?></td>
                            </tr> <?php endforeach; ?> </tbody>
                </table>
            </div>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4"> <?php $aula['nota'] = $aula['nota'] ? $aula['nota'] : 'Não houveram observações anotadas nesta aula!' ?> <div class="flex-1 min-w-25"><label class="block text-gray-500 text-xs">Notas da Aula</label>
                <div class="border border-gray-300 rounded-md px-2 w-full focus:outline-none focus:ring-1 focus:ring-blue-300 focus:border-blue-500"><?= $aula['nota'] ?></div>
            </div>
            <div class="flex flex-col md:flex-row justify-center items-center gap-4 pt-4"><button type="button" onclick="window.history.back()" class="w-40 px-12 py-1 bg-blue-400 text-white rounded font-medium hover:bg-blue-600 shadow-md cursor-pointer">Voltar</button></div>
        </div>
    </div>
</div>