<?php $this->layout('layout::home-usuario'); ?>
<?php $urlCompleta = $_SERVER['REQUEST_URI'];
$url = parse_url($urlCompleta, PHP_URL_QUERY); ?>
<?php
if ($mensagensSucesso):
    $this->message = $this->escapeHtml($mensagensSucesso);
endif;
?>
<!DOCTYPE html>
<html lang="pt-BR" class="h-full">

<body class="h-full antialiased">
    <div class="min-h-full">
        <header class="bg-white">
            <div class="max-w-7xl mx-auto pt-4 pb-1">
                <h1 class="bg-white text-xl sm:text-[22px] text-center text-blue-600 max-w-full">Perfil dos atletas de <?php echo $this->user_name ?> </h1>
            </div> <?php if ($this->message): ?> <div class="col-span-12 mb-6">
                    <div rows="3" class="field-sizing-content mt-1 block w-full border border-red-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-primary focus:border-primary text-red-700"> <?= $this->escapeHtml($this->message) ?> </div>
                </div> <?php endif; ?>
        </header> <?php if (count($this->atletas) === 0) { ?> <p class="text-gray-500 italic flex justify-center mt-6">Nenhum atleta cadastrado até o momento</p><a href="javascript:history.go(-1)" class="col-span-4 md:col-span-2 text-blue-700 text-base flex justify-center items-center mt-5"><span class="material-icons-regular text-lg">Arrow_Back</span>voltar</a> <?php } else { ?> <main class="max-w-7xl pb-10 lg:py-12"> <?php foreach ($this->atletas as $atleta): ?> <div class="lg:grid lg:grid-cols-12">
                        <aside class="px-2 sm:px-1 lg:py-0 lg:px-0 lg:col-span-3">
                            <nav class="space-y-1"><br><a href="/editar_atleta/<?= $atleta['id'] ?>">
                                    <li class="sm:text-sm rounded-md hover:bg-slate-200 indent-2 p-1 w-full flex float:left items-center"><span class="material-icons-regular mr-1 text-[20px] text-[#a15959]">face</span> Editar perfil do Atleta<br>&nbsp;&nbsp;&nbsp;<?= $atleta['nome'] ?> </li>
                                </a><br> <?php $urlNome = rawurlencode($atleta['nome']); ?> <a href="/aulas/presentes/<?= $urlNome ?>" title="visualizar as aulas que seu atleta participou">
                                    <li class="sm:text-sm rounded-md hover:bg-slate-200 indent-2 p-1 w-full flex float:left items-center"><span class="material-icons-regular mr-1 text-[20px] text-[#a15959]">face</span> Aulas do Atleta (presenças)<br>&nbsp;&nbsp;&nbsp;<?= $atleta['nome'] ?> </li>
                                </a><br><a href="/aulas/ausentes/<?= $urlNome ?>" title="visualizar as aulas que seu atleta participou">
                                    <li class="sm:text-sm rounded-md hover:bg-slate-200 indent-2 p-1 w-full flex float:left items-center"><span class="material-icons-regular mr-1 text-[20px] text-[#a15959]">face</span> Aulas do Atleta (ausencias):<br>&nbsp;&nbsp;&nbsp;<?= $atleta['nome'] ?> </li>
                                </a><br><a href="/usuario" title="<?php echo $this->user_name ?>">
                                    <li class="sm:text-sm rounded-md hover:bg-slate-200 indent-2 p-1 w-full flex float:left items-center"><span class="material-icons-regular mr-1 text-[24px] text-[#a15959]">Manage_Accounts</span> Voltar para o Titular:<br>&nbsp;&nbsp;&nbsp;<?php echo $this->user_name ?> </li>
                                </a></nav>
                        </aside>
                        <div class="space-y-6 sm:px-6 lg:px-0 lg:col-span-8">
                            <div>
                                <div class="shadow sm:rounded-lg sm:overflow-hidden bg-white">
                                    <div class="bg-white py-6 px-4 sm:p-6">
                                        <div>
                                            <h2 class="mt-3 block w-full border-gray-300 shadow-sm px-2 pt-0.5 sm:text-sm bg-blue-200 rounded-md text-lg font-semi-bold text-gray-900">PERFIL DO ATLETA</h2>
                                        </div>
                                        <div class="mt-5 grid grid-cols-12 gap-6">
                                            <div class="col-span-12 sm:col-span-6"><label class="block text-sm font-medium text-gray-900">Nome:</label> <span class="mt-1 block w-full border-b border-gray-300 shadow-sm px-2 sm:text-sm"><?= $atleta['nome'] ?><span></span></span></div>
                                            <div class="col-span-12 sm:col-span-6"><label class="block text-sm font-medium text-gray-900">Titular:</label> <span class="mt-1 block w-full border-b border-gray-300 shadow-sm px-2 sm:text-sm"><?= $atleta['titular'] ?><span></span></span></div>
                                            <div class="col-span-12 sm:col-span-6"><label class="block text-sm font-medium text-gray-900">Nascimento:</label> <span class="mt-1 block w-full border-b border-gray-300 shadow-sm px-2 sm:text-sm"> <?= strlen($atleta['nascimento']) === 8 ? substr($atleta['nascimento'], 0, 2) . '/' . substr($atleta['nascimento'], 2, 2) . '/' . substr($atleta['nascimento'], 4, 4) : $atleta['nascimento'] ?><span></span></span></div>
                                            <div class="col-span-12 sm:col-span-6"><label class="block text-sm font-medium text-gray-900">Patins:</label> <span class="mt-1 block w-full border-b border-gray-300 shadow-sm px-2 sm:text-sm"><?= $atleta['patins'] ?><span></span></span></div>
                                            <div class="col-span-12 sm:col-span-6"><label class="block text-sm font-medium text-gray-900">Turma 01:</label> <span class="mt-1 block w-full border-b border-gray-300 shadow-sm px-2 sm:text-sm"><?= $atleta['turma01'] ?><span></span></span></div>
                                            <div class="col-span-12 sm:col-span-6"><label class="block text-sm font-medium text-gray-900">Turma 02:</label> <span class="mt-1 block w-full border-b border-gray-300 shadow-sm px-2 sm:text-sm"><?= $atleta['turma02'] ?><span></span></span></div>
                                            <div class="col-span-12 sm:col-span-6"><label class="block text-sm font-medium text-gray-900">Turma 02:</label> <span class="mt-1 block w-full border-b border-gray-300 shadow-sm px-2 sm:text-sm"><?= $atleta['turma03'] ?><span></span></span></div>
                                            <div class="col-span-12 sm:col-span-6"><label class="block text-sm font-medium text-gray-900">Cadastro:</label> <span class="mt-1 block w-full border-b border-gray-300 shadow-sm px-2 sm:text-sm">
 <?php $dataUs = $atleta['cadastro'];
$date = new DateTime($dataUs);
 echo $date->format('d-m-Y H:m'); ?>
<span></span></span></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?> </main> <?php } ?>
    </div>
</body>

</html>