<?php $this->layout('layout::home-usuario'); ?>

<?php $this->headTitle('aulas Cadastrados'); ?>

<h1 class="text-2xl m-4 ml-1 text-blue-600">Aulas </h1>

<?php if ($this->mensagensSucesso):
    $this->message = $this->escapeHtml($mensagensSucesso);
endif; ?>
<?php
if ($this->message): ?>
    <span
        class="scroll-mt-[5.1rem] sm:scroll-mt-28 md:scroll-mt-32 lg:scroll-mt-0  flex items-center mt-6 mx-12">
        <span class="h-px flex-1 bg-blue-400"></span>
        <h2 class="shrink-0 px-4 text-blue-700"><?= $this->escapeHtml($this->message) ?></h2>
        <span class="h-px flex-1 bg-blue-400"></span>
    </span><br /><br />
<?php endif; ?>

<?php if ($this->mensagensErro):
    $this->messageErro = $this->escapeHtml($mensagensErro);
endif; ?>
<?php if ($this->messageErro): ?>
    <span
        class="scroll-mt-[5.1rem] sm:scroll-mt-28 md:scroll-mt-32 lg:scroll-mt-0  flex items-center mt-6 mx-12">
        <span class="h-px flex-1 bg-red-400"></span>
        <h2 class="shrink-0 px-4 text-red-700"><?= $this->escapeHtml($this->messageErro) ?></h2>
        <span class="h-px flex-1 bg-red-400"></span>
    </span><br /><br />
<?php return;
endif; ?>

<?php if (isset($this->tipoConsulta)) { ?>
    <a href="javascript:history.go(-1)" class="col-span-4 md:col-span-2  text-green-700">
        <span class="text-[clamp(0.9rem,3vw,1rem)] flex justify-center mt-9 mb-9">
            <= voltar para o(a) atleta <?= $this->escapeHtml($this->atleta) ?></span></a>
    </a>
<?php }  ?>

<?php if (count($this->aulas) < 1): ?>
    <?php
    $consulta = $this->escapeHtml($this->tipoConsulta) ? ', em que seu atleta está incluído na lista dos ' .  $this->escapeHtml($tipoConsulta) : ''; ?>
    <span
        class="scroll-mt-[5.1rem] sm:scroll-mt-28 md:scroll-mt-32 lg:scroll-mt-0  flex items-center mt-6 mx-12">
        <span class="h-px flex-1 bg-blue-400"></span>
        <h2 class="px-4 text-blue-700">Nenhuma aula cadastrada até o momento <?= $consulta ?></h2>
        <span class="h-px flex-1 bg-blue-400"></span>
    </span>
<?php else: ?>
    <div class="table-container w-full">
        <h2 class="text-mb text-gray-800 mb-4 pb-2 ML-4">
            Exibindo: <span class="text-blue-600"><?= $mesExibicao ?></span>
        </h2>

        <table class="custom-table whitespace-nowrap mb-4">
            <thead>
                <tr>
                    <?php if ($this->escapeHtml($this->role) !== 'titular'): ?>
                        <th>Comandos</th>
                    <?php endif; ?>
                    <th>Data</th>
                    <th>Local</th>
                    <th>Nivel</th>
                    <th>Dia</th>
                    <th>Início</th>
                    <th>Término</th>
                    <th>Monitor</th>
                    <th>Monitor1</th>
                    <th>Monitor2</th>
                    <th>Presentes</th>
                    <th>Ausentes</th>
                </tr>
            </thead>
            <?php
            $dataAnterior = null;
            foreach ($this->aulas as $aula):
                $dataAtual = DateTime::createFromFormat('Ymd', $aula['data'])->format('d/m/Y');

                if ($dataAtual !== $dataAnterior): ?>
                    <!-- Separador de Dia -->
                    <tr class="bg-gray-50">
                        <td colspan="3" class="pl-3 pt-3 text-sm text-gray-600  border-blue-300 text-center">
                           <?= $dataAtual ?>
                        </td>
                    </tr>
                <?php
                    $dataAnterior = $dataAtual;
                endif;
                ?>
                <?php $formatarHora = fn($h) => substr_replace(str_pad((string)$h, 4, '0', STR_PAD_LEFT), ':', 2, 0); ?>

                <?php
                $aula['inicio_formatado'] = $formatarHora($aula['inicio']) . 'hs';
                $aula['termino_formatado'] = $formatarHora($aula['termino']) . 'hs';
                //  TRATAR data PARA EXIBIÇÃO (20261210 -> 10/12/2026)
                $formatarData = fn($h) => date('d/m/Y', strtotime((string)$aula['data']));
                $aula['data_formatada']  =  $formatarData($aula['data']);
                ?>
                <tbody>
                    <tr>
                        <?php if ($this->escapeHtml($this->role) !== 'titular'): ?>
                            <td>
                                <a href="<?= $this->url('aula.editar', ['id' => $aula['id']]) ?>" class="text-blue-600 hover:underline mr-1">
                                    Editar
                                </a>
                                <a href="<?= $this->url('aula.excluir', ['id' => $aula['id']]) ?>"
                                    onclick="return confirm('Tem certeza que deseja excluir <?= $aula['id'] ?> ?')"
                                    class="text-red-300 hover:underline">
                                    Excluir
                                </a>
                            </td>
                        <?php endif; ?>
                        <td><?= $aula['data_formatada'] ?></td>
                        <td><?= $aula['local'] ?></td>
                        <td><?= $aula['nivel'] ?></td>
                        <td><?= $aula['dia'] ?></td>
                        <td><?= $aula['inicio_formatado'] ?></td>
                        <td><?= $aula['termino_formatado'] ?></td>
                        <td><?= $aula['monitor'] ?></td>
                        <td><?= $aula['monitor1'] ?></td>
                        <td><?= $aula['monitor2'] ?></td>
                        <td><?= $aula['presentes'] ?></td>
                        <td><?= $aula['ausentes'] ?></td>
                    </tr>

                </tbody>
            <?php endforeach; ?>
        </table>
    </div>

  <?php if($this->role === 'admin' || $this->role === 'monitor') : ?>  
    <div class="bg-white p-6 pb-1 md:flex md:w-full rounded-lg">
        <form method="GET" class="flex flex-wrap items-end gap-4">
            <!-- Parâmetros ocultos -->
            <input type="hidden" name="atleta" value="<?= $atleta ?>">
            <input type="hidden" name="chama" value="<?= $tipoConsulta ?>">

            <div class="flex-1 min-w-50">
                <label class="block text-sm text-gray-700 mb-1">Navegar por Mês:</label>
                <select name="mes" onchange="this.form.submit()" class="w-40 border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 text-sm p-2 border">
                    <option value="" selected>selecione</option>
                    <?php foreach ($opcoesMeses as $valor => $rotulo): ?>
                        <option value="<?= $valor ?>" <?= $valor == $mesAtual ?: '' ?>><?= $rotulo ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </form>

        <form method="GET" class="flex flex-wrap items-end gap-4">
            <div class="flex min-w-80 pt-4 items-center">
                <label class="text-sm text-gray-700 mb-1 w-32">Data Específica -> </label>
                <div class="flex gap-2">
                    <input type="date" onchange="this.form.submit()" name="data_especifica" value="<?= $dataBusca ?>" class="w-9 border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 text-sm p-2 border">
                </div>
            </div>

    </div>
    <?php endif; ?>
<?php endif; ?>