<?php $this->layout('layout::home-usuario'); ?> 

<div class="mt-3 flex items-center justify-center">
    <div class="p-2 bg-white rounded-lg shadow-md border border-gray-200"> 
        
    <?php if (isset($_GET['error']) && $_GET['error'] === 'link-expirado'): ?> <div class="max-w-100 text-center m-auto mb-5 text-blue-800 hyphens-none">O link de recuperação expirou ou é inválido. Por favor, solicite um novo no link ' senha' abaixo.</div> <?php endif; ?>

        <?php if (isset($_GET['msg']) && $_GET['msg'] === 'nao_consta'): ?>
            <div class="max-w-100 text-center m-auto mb-5 text-blue-800 hyphens-none">Seu email não consta na base de dados. Para cadastrar-se utilize o link "Fazer meu cadastro" abaixo do botão azul.</div>
        <?php endif; ?>

        <?php if (!empty($message)): ?>
            <div><?= $message ?></div> <?php endif; ?> <h2 class="text-3xl text-center text-gray-800 mb-1">Seu login na Axel</h2>

        <?php if ($this->error): ?>
            <div class="p-3 mb-4 text-base text-red-700 bg-red-100 rounded-lg border border-red-200"> <?= $this->error ?> </div> <?php endif; ?>

        <form method="post" action="">
            <div class="relative w-full max-w-full p-6 bg-white rounded-xl">
                <div class="relative w-full max-w-sm mx-auto mb-5"><label class="block text-base text-gray-600 mb-2">E-mail ou Telefone cadastrados</label>
                    <div class="relative flex items-center group">
                        <div class="absolute left-4 text-emerald-700 transition-all duration-300"><svg id="userIcon" xmlns="http://w3.org" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                                <path id="iconPath" stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
                            </svg></div><input id="username" name="username" type="text" oninput="mascaraTelefoneEmail(this)" placeholder="E-mail ou Telefone" class="w-full pl-12 pr-4 py-1.5 text-base border-2 border-gray-200 rounded-lg focus:border-emerald-600 focus:outline-none" maxlength="50">
                    </div>
                </div><label for="password" class="block text-base text-gray-600 mt-5 mb-2">Senha</label>
                <div><input name="password" id="password" type="password" required placeholder="Digite sua senha" class="w-full pl-4 text-base pr-12 py-1.5 border-2 border-gray-200 rounded-lg focus:border-emerald-600 focus:outline-none"> <button type="button" onclick="togglePassword()" class="cursor-pointer absolute right-7 top-38 p-1 text-emerald-700 hover:text-emerald-800 transition-colors focus:outline-none"><svg id="eyeIcon" class="w-6 h-6" focusable="false" aria-hidden="true" viewBox="0 0 24 24" fill="currentColor">
                            <path d="M12 7c2.76 0 5 2.24 5 5 0 .65-.13 1.26-.36 1.83l2.92 2.92c1.51-1.26 2.7-2.89 3.43-4.75-1.73-4.39-6-7.5-11-7.5-1.4 0-2.74.25-3.98.7l2.16 2.16C10.74 7.13 11.35 7 12 7zM2 4.27l2.28 2.28.46.46C3.08 8.3 1.78 10.02 1 12c1.73 4.39 6 7.5 11 7.5 1.55 0 3.03-.3 4.38-.84l.42.42L19.73 22 21 20.73 3.27 3 2 4.27zM7.53 9.8l1.55 1.55c-.05.21-.08.43-.08.65 0 1.66 1.34 3 3 3 .22 0 .44-.03.65-.08l1.55 1.55c-.67.33-1.41.53-2.2.53-2.76 0-5-2.24-5-5 0-.79.2-1.53.53-2.2zm4.31-.78 3.15 3.15.02-.16c0-1.66-1.34-3-3-3l-.17.01z"></path>
                        </svg></button></div>
            </div>
            <div class="flex flex-col justify-end items-center mb-1"><button type="submit" class="p-1 center cursor-pointer w-50 bg-blue-500 hover:bg-blue-700 text-white font-semi-bold rounded-lg">Entrar</button></div>
        </form>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-3 min-w-full">
            <div class="md:col-span-1 text-base text-gray-600 mt-3 md:mt-4 text-left md:text-center"><a class="text-base text-blue-600" href="/minha_senha">Perdi minha senha</a></div>
            <div class="md:col-span-1 text-base text-gray-600 mt-3 md:mt-4 text-right"><a class="text-base text-blue-600" href="/minha_senha">Mudar minha senha</a></div>
            <div class="md:col-span-1 text-base text-gray-600 text-left md:text-center"><a class="text-base text-blue-600" href="/novo_usuario">Fazer o cadastro</a></div>
            <div class="md:col-span-1 text-base text-gray-600 text-left md:text-center"><a title="se o seu e-mail registrado aqui na Axel é do Gmail, click aqui e você não precisará de senha" class="text-base text-blue-600 flex items-center" href="/auth/google/callback"><img class="h-5 mr-2" src="/img/google.ico" alt="Google logo"> Entrar com Google</a></div>
            <div class="col-span-2 text-base text-gray-600 text-center w-full"><a class="text-base text-blue-600 flex justify-center" href="https://wa.me/5551993340678?text=Consulta+por+whatsApp+sobre+d%C3%BAvidas+no+login+do+site"><img class="h-5 mr-2" src="/img/whats.png" alt="whatsApp logo"> Dúvidas? consulte por whatsApp</a></div>
        </div>
    </div>
</div>
<script type="text/javascript" src="/js/login.js"></script>