<!-- src/App/templates/app/reset-password.phtml -->
<?php $this->layout('layout::home-usuario'); ?>

<div class="mt-10 flex items-center justify-center">
    <div class="max-w-md p-2 bg-white rounded-lg shadow-md border border-gray-200">
        <h2 class="text-2xl  text-center text-gray-800 mb-6">Definir Nova Senha</h2>
        <span class="text-sm text-center block px-4 hyphens-none">Crie uma senha segura para sua conta, com um mínimo de 6 dígitos - contendo no mínimo 1 letra e no mínimo 1 número</span><br />


        <?php if (isset($this->error)): ?>
            <div style="color: red; margin-bottom: 15px;">
                <?= $this->error ?>
            </div>
        <?php endif; ?>

        <form method="post" action="">
            <!-- O token que veio na URL deve ser enviado no POST -->
            <input type="hidden" name="token" value="<?= $this->token ?>">

            <div class="mb-4">

                <label for="new_password" class="block text-sm  text-gray-600 mb-1">Nova Senha:</label>
                <input type="password" name="new_password" id="new_password" required placeholder="******" minlength="6" class="w-full p-2 border rounded focus:ring-2 focus:ring-blue-500 outline-none border-gray-300">

            </div>



            <div class="form-group">

                <label for="confirm_password" class="block text-sm  text-gray-600 mb-1">Confirme a Nova Senha:</label>
                <input type="password" name="confirm_password" id="confirm_password" required  placeholder="******" minlength="6" class="w-full p-2 border rounded focus:ring-2 focus:ring-blue-500 outline-none border-gray-300">


            </div>
            <button type="submit" class="mt-6 p-1text-sm cursor-pointer w-full bg-blue-500 hover:bg-blue-700 text-white font-semi-bold rounded transition">Alterar Senha</button>
        </form>
    </div>
</div>