<!DOCTYPE html>

<html lang="pt-BR">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <link rel="canonical" href="https://axelpatinacao.com.br" />
    <link rel="icon" href="/img/favicon-452x452.png" sizes="452x452" type="image/png" />
    <link rel="icon" href="/img/favicon-256x256.ico" sizes="256x256" type="image/x-icon" />
    <link rel="icon" href="/img/favicon-192x192.ico" sizes="192x192" type="image/x-icon" />
    <link rel="icon" href="/img/favicon-32x32.ico" sizes="32x32" type="image/x-icon" />
    <link rel="icon" href="/img/favicon-16x16.ico" sizes="16x16" type="image/x-icon" />

    <title>AXEL Patinação Artística</title>

    <link rel="preload" href="/css/output.css" as="style">
    <link rel="stylesheet" href="/css/output.css" media="print" onload="this.media='all'">
</head>

<body
    class="flex flex-col min-h-screen text-[#161616] text-justify hyphens-auto max-w-full overflow-x-hidden box-border no-underline p-[0.1vw_0] m-0 leading-inherit roboto"
    id="escola-dedicada-a-formacao-esportiva-artistica-e-humana-por-meio-da-patinacao">
    <header>

    </header>

    <main class="grow">
        <?= $this->content; ?>
    </main>
    
    <div class="bg-gray-300 w-full text-center mt-10">
        ©2025 Axel Patinação Artística. Todos os direitos reservados.
    </div>

    <a href="#escola-dedicada-a-formacao-esportiva-artistica-e-humana-por-meio-da-patinacao"
        class="hidden min-[1024px]:block fixed bottom-4 right-3 z-50 rounded-full bg-[#b15959] p-2 text-white shadow-lg transition-all duration-300 hover:bg-[#a15959] hover:scale-110">
        <span class="material-icons-regular text-[20px]">Arrow_Upward</span> inicio
    </a>

</body>

</html>