<!DOCTYPE html>
<html lang="pt-BR">

<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width,initial-scale=1">
   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
   <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
   <meta http-equiv="Pragma" content="no-cache">
   <meta http-equiv="Expires" content="0">
   <link rel="icon" href="/img/favicon-452x452.png" sizes="452x452" type="image/png">
   <link rel="icon" href="/img/favicon-256x256.ico" sizes="256x256" type="image/x-icon">
   <link rel="icon" href="/img/favicon-192x192.ico" sizes="192x192" type="image/x-icon">
   <link rel="icon" href="/img/favicon-32x32.ico" sizes="32x32" type="image/x-icon">
   <link rel="icon" href="/img/favicon-16x16.ico" sizes="16x16" type="image/x-icon">
   <title>AXEL Patinação Artística</title>
   <meta property="title" content="AXEL Patinação Artística">
   <meta name="description" content="A Axel Patinação Artística é uma escola de patinação dedicada à formação esportiva, artística e humana por meio da patinação.
   Desde a sua criação, a Axel tem como missão promover o desenvolvimento técnico e emocional de seus alunos, unindo disciplina, sensibilidade e espírito de equipe em cada aula e apresentação. Mais do que ensinar a patinar, acreditamos no poder transformador do esporte como ferramenta de inclusão e crescimento pessoal. 
   Por isso, a Axel também atua em projetos sociais, oferecendo acesso gratuito à prática da patinação para crianças e adolescentes em situação de vulnerabilidade, incentivando a superação e a construção de novos caminhos através do movimento e da arte.
   Nossos valores estão baseados no respeito, na empatia, na cooperação e na busca constante pela excelência. Cada aluno é visto como parte essencial de uma grande equipe, onde o aprendizado vai além da técnica, forma caráter, fortalece vínculos e inspira sonhos. Na Axel, acreditamos que o verdadeiro brilho está em cada conquista compartilhada e no amor pelo que se faz. Conheça nossa pista de patinação.">
   <meta property="og:type" content="website">
   <meta property="og:url" content="https://axelpatinacao.com.br/">
   <meta property="og:locale" content="pt_BR">
   <meta property="og:title" content="AXEL Patinação Artística">
   <meta property="og:image" content="https://axelpatinacao.com.br/img/logo.png">
   <meta property="og:image:secure_url" content="https://axelpatinacao.com.br/img/logo.png">
   <meta property="og:image:type" content="image/png">
   <meta property="og:image:width" content="3840">
   <meta property="og:image:height" content="960">
   <meta property="og:image:alt" content="Axel Patinação Artística">
   <meta property="og:description" content="A Axel Patinação Artística é uma escola dedicada à formação esportiva, artística e humana por meio da patinação. Em Cachoeirinha e Canoas RS no Rio Grande do Sul, bem pertinho de Porto Alegre.
   Desde a sua criação, a Axel tem como missão promover o desenvolvimento técnico e emocional de seus alunos, unindo disciplina, sensibilidade e espírito de equipe em cada aula de patinação e apresentação. Mais do que ensinar a patinar, acreditamos no poder transformador do esporte como ferramenta de inclusão e crescimento pessoal. 
   Por isso, a Axel também atua em projetos sociais, oferecendo acesso gratuito à prática da patinação para crianças e adolescentes em situação de vulnerabilidade, escola de patins incentivando a superação e a construção de novos caminhos através do movimento e da arte.
   Nossos valores estão baseados no respeito, na empatia, na cooperação e na busca constante pela excelência. Cada aluno é visto como parte essencial de uma grande equipe, onde o aprendizado vai além da técnica, forma caráter, fortalece vínculos e inspira sonhos. Na Axel, acreditamos que o verdadeiro brilho está em cada conquista compartilhada e no amor pelo que se faz.">
   <link rel="preload" href="/css/output.css" as="style">
   <link rel="stylesheet" href="/css/output.css" media="print" onload="this.media='all'">
</head>

<?= $this->content; ?>

 <footer class="bg-gray-300 text-center text-gray-700 w-full text-sm mt-4">©2025 Axel Patinação Artística - Todos os direitos reservados.</footer><a href="#escola-dedicada-a-formacao-esportiva-artistica-e-humana-por-meio-da-patinacao" class="hidden min-[1024px]:block fixed bottom-4 right-3 z-50 rounded-full bg-[#b15959] p-2 text-white shadow-lg transition-all duration-300 hover:bg-[#a15959] hover:scale-110"><span class="material-icons-regular text-[20px]">Arrow_Upward</span> inicio</a>

</html>