<!DOCTYPE html>
<html lang="pt-BR">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <link rel="icon" href="/img/favicon-452x452.png" sizes="452x452" type="image/png">
  <link rel="icon" href="/img/favicon-256x256.ico" sizes="256x256" type="image/x-icon">
  <link rel="icon" href="/img/favicon-192x192.ico" sizes="192x192" type="image/x-icon">
  <link rel="icon" href="/img/favicon-32x32.ico" sizes="32x32" type="image/x-icon">
  <link rel="icon" href="/img/favicon-16x16.ico" sizes="16x16" type="image/x-icon">
  <title>AXEL Patinação Artística</title>
  <link rel="preload" href="/css/output.css" as="style">
  <link rel="stylesheet" href="/css/output.css" media="print" onload="this.media='all'">
</head>

<body class="flex flex-col min-h-screen text-[#161616] text-justify hyphens-auto max-w-full box-border no-underline p-[0.1vw_0] m-0 leading-inherit roboto overflow-y-scroll" id="escola-dedicada-a-formacao-esportiva-artistica-e-humana-por-meio-da-patinacao">

  <header class="fixed flex items-center w-full max-w-337 bg-blue-100 z-50">
    <div class="max-w-35 py-1">
      <a href="/">
        <img src="/img/logo.png" alt="exibe o logo da Axel Patinação" loading="lazy" class="max-w-35 h-auto min-w-25">
      </a>
    </div>

    <div class="whitespace-nowrap w-full max-w-full items-center justify-end hidden md:flex md:order-1 pr-10">
      <nav class="flex justify-end items-center bg-neutral-primary w-full max-w-full z-10 mt-0 inset-s-0">
        <ul class="text-[14px] flex flex-col justify-end rounded-base bg-neutral-secondary-soft md:flex-row md:bg-neutral-primary max-w-full text-right gap-2"> <?php $path = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);  ?> <a href="/" title="Blog - Página inicial">
            <li class="rounded-md hover:bg-slate-200 indent-0.5 w-10 flex float:left items-center"><span class="material-icons-regular text-[19px] text-[#a15959]">home</span></li>
          </a> <?php if ((!isset($this->user_role) || $this->user_role === 'guest') && $path !== '/login'): ?> <a href="/login" title="Execute seu login na Axel">
              <li class="rounded-md hover:bg-slate-200 indent-0.5 w-40 flex float:left items-center"><span class="material-icons-regular text-[19px] text-[#a15959]">Key</span> Login / entrar</li>
            </a> 
            <?php endif; ?> 
            <?php if ((!isset($this->user_role) || $this->user_role === 'guest') && $path !== '/minha_senha'): ?> <a href="/minha_senha" title="Solicite uma nova senha">
              <li class="rounded-md hover:bg-slate-200 indent-0.5 w-32 flex float:left items-center"><span class="material-icons-regular text-[19px] text-[#a15959]">Key</span> Minha senha</li>
            </a> <?php endif; ?> 
            <?php if ((!isset($this->user_role) || $this->user_role === 'guest'  || $this->user_role === 'admin') && $path !== '/novo_usuario'): ?> <a href="/novo_usuario" title="Criar seu usuário">
              <li class="rounded-md hover:bg-slate-200 indent-0.5 w-31 flex float:left items-center"><span class="material-icons-regular text-[19px] text-[#a15959]">Breastfeeding</span>Cadastro</li>
            </a> <?php endif; ?> <?php if ($this->user_role && ($this->user_role === 'admin' || $this->user_role === 'monitor') && $path !== '/nova_turma'): ?> <a href="/nova_turma" title="Criar uma nova turma">
              <li class="rounded-md hover:bg-slate-200 indent-0.5 w-26 flex float:left items-center"><span class="material-icons-regular text-[19px] text-[#a15959]">Manage_Accounts</span> Nova turma</li>
            </a> <?php endif; ?>

          <?php if (isset($this->user_role) && ($this->user_role === 'admin' || $this->user_role === 'titular') && $path !== '/novo_atleta'): ?> <a href="/novo_atleta" title="Registrar um atleta">
              <li class="rounded-md hover:bg-slate-200 indent-0.5 w-27 flex float:left items-center"><span class="material-icons-regular text-[19px] text-[#a15959]">face</span> Novo Atleta</li>
            </a> <?php endif; ?>

          <?php if (isset($this->user_role) && $this->user_role !== 'guest' && $this->user_role !== 'usuario' && $path !== '/atletas'): ?> <a href="/atletas" title="Listar os atletas">
              <li class="rounded-md hover:bg-slate-200 indent-0.5 w-20 flex float:left items-center"><span class="material-icons-regular text-[19px] text-[#a15959]">face</span> Atletas</li>
            </a> <?php endif; ?> 
            
                        <?php if (isset($this->user_role) && $this->user_role === 'titular' && $path === '/usuario'): ?>
              <a href="https://axelpatinacao.basedeclientes.com.br" target="_blank" title="Área financeira da Axel">
                <li class="rounded-md hover:bg-slate-200 indent-0.5 w-26 flex float:left items-center"><span class="material-icons-regular text-[19px] text-[#a15959]">Attach_Money</span> Financeiro</li>
              </a>
            <?php endif; ?>
            
            
            <?php if (isset($this->user_role) && $this->user_role !== 'guest' && $this->user_role !== 'usuario' && $this->user_role !== 'titular' && $path !== '/aulas'): ?> <a href="/aulas" title="Listar as aulas anteriores">
              <li class="rounded-md hover:bg-slate-200 indent-0.5 w-20 flex float:left items-center"><span class="material-icons-regular text-[19px] text-[#a15959]">Manage_Accounts</span> Aulas</li>
            </a> <?php endif; ?> 
            <?php if ((isset($this->user_role) && ($this->user_role === 'admin' || $this->user_role === 'monitor')) && $path !== '/turmas'): ?> <a href="/turmas" title="Listar todas as turmas">
              <li class="rounded-md hover:bg-slate-200 indent-0.5 w-20 flex float:left items-center"><span class="material-icons-regular text-[19px] text-[#a15959]">Manage_Accounts</span> Turmas</li>
            </a> <?php endif; ?> <?php if ($this->user_role && $this->user_role === 'admin' && $path !== '/usuarios'): ?> <a href="/usuarios" title="Listar os usuários">
              <li class="rounded-md hover:bg-slate-200 indent-0.5 w-17 flex float:left items-center font-semi-bold"><span class="material-icons-regular text-[19px] text-[#a15959]">Breastfeeding</span> Users</li>
            </a> <?php endif; ?> <?php if ($this->user_role && $this->user_role !== 'guest'): ?> <a href="/logout" title=" Sair/Logout ">
              <li class="rounded-md hover:bg-slate-200 indent-0.5 w-7 flex float:left items-center font-semi-bold"><span class="material-icons-regular text-[19px] text-[#a15959]">Door_Open</span></li>
            </a> <?php endif; ?> <?php if (($this->user_role && $this->user_role !== 'guest') && $path !== '/usuario'): ?> <a href="/usuario" title="<?php echo $this->user_name ?>">
              <li class="rounded-md hover:bg-slate-200 indent-0.5 w-15 flex float:left items-center"><span class="material-icons-regular text-[19px] text-[#a15959]">Manage_Accounts</span></li>
            </a> <?php endif; ?> </ul>
      </nav>
    </div>
    <div id="containerMenu" class="fixed block top-4 right-9 z-50">
      <label class="w-8 h-8 cursor-pointer flex flex-col items-center justify-center rounded-md bg-white shadow-md absolute">
        <input id="botaoMenu" class="hidden peer" type="checkbox">
        <div class="w-5 h-0.5 bg-black mb-1 transition-all duration-300 peer-checked:rotate-45 peer-checked:translate-y-1.5"></div>
        <div class="w-5 h-0.5 bg-black mb-1 transition-all duration-300 peer-checked:opacity-0"></div>
        <div class="w-5 h-0.5 bg-black transition-all duration-300 peer-checked:-rotate-45 peer-checked:-translate-y-1.5"></div>
        <nav class="absolute opacity-0 invisible  top-8 w-60 translate-x-5 peer-checked:opacity-100 peer-checked:visible peer-checked:translate-x-0 transition-all duration-300 bg-white shadow-2xl rounded-lg p-2 border border-gray-100 text-md text-gray-600">
          <ul class="flex flex-col"> <?php if (($this->user_role && $this->user_role !== 'guest') && $path !== '/usuario'): ?> <a href="/usuario">
                <li class="rounded-md hover:bg-slate-200 indent-0.5 w-40 flex float:left items-center"><span class="material-icons-regular text-[19px] text-[#a15959] mr-2">Manage_Accounts</span>
                  <?php $partes = explode(' ', $this->user_name);
                                        echo $primeiro = array_shift($partes); ?>
                </li>
              </a>
            <?php endif; ?>
            <a href="/">
              <li class="rounded-md hover:bg-slate-200 indent-0.5 w-40 flex float:left items-center"><span class="material-icons-regular text-[19px] text-[#a15959]">home</span> Blog inicial</li>
            </a>
            <?php if ((!isset($this->user_role) || $this->user_role === 'guest') && $path !== '/login'): ?> <a href="/login" title="Execute seu login na Axel">
                <li class="rounded-md hover:bg-slate-200 indent-0.5 w-35 flex float:left items-center"><span class="material-icons-regular text-[19px] text-[#a15959]">Key</span> Login / entrar</li>
              </a> <?php endif; ?> <?php if ((!isset($this->user_role) || $this->user_role === 'guest') && $path !== '/minha_senha'): ?> <a href="/minha_senha" title="Solicite uma nova senha">
                <li class="rounded-md hover:bg-slate-200 indent-0.5 w-40 flex float:left items-center"><span class="material-icons-regular text-[19px] text-[#a15959]">Key</span>Perdi a senha</li>
              </a> <?php endif; ?> <?php if ((!isset($this->user_role) || $this->user_role === 'guest') && $path !== '/minha_senha'): ?> <a href="/minha_senha" title="Solicite uma nova senha">
                <li class="rounded-md hover:bg-slate-200 indent-0.5 w-40 flex float:left items-center"><span class="material-icons-regular text-[19px] text-[#a15959]">Key</span>Mudar a senha</li>
              </a> <?php endif; ?> <?php if ((!isset($this->user_role) || $this->user_role === 'guest' || $this->user_role === 'admin') && $path !== '/novo_usuario'): ?> <a href="/novo_usuario" title="Registrar um usuário">
                <li class="rounded-md hover:bg-slate-200 indent-0.5 w-35 flex float:left items-center"><span class="material-icons-regular text-[19px] text-[#a15959]">Breastfeeding</span> Novo usuário</li>
              </a> <?php endif; ?> <?php if ($this->user_role && $this->user_role === 'admin' && $path !== '/usuarios'): ?> <a href="/usuarios" title="Listar os usuários">
                <li class="rounded-md hover:bg-slate-200 indent-0.5 w-40 pt-0 flex float:left items-center font-semi-bold"><span class="material-icons-regular text-[19px] text-[#a15959]">Breastfeeding</span> Listar usuários</li>
              </a> <?php endif; ?> <?php if (isset($this->user_role) && ($this->user_role === 'admin' || $this->user_role === 'titular') && $path !== '/novo_atleta'): ?> <a href="/novo_atleta" title="Registrar um atleta">
                <li class="rounded-md hover:bg-slate-200 indent-0.5 w-40 flex float:left items-center"><span class="material-icons-regular text-[19px] text-[#a15959]">face</span>Novo atleta</li>
              </a> <?php endif; ?>

            <?php if (isset($this->user_role) && $this->user_role !== 'guest' && $this->user_role !== 'usuario' && $path !== '/atletas'): ?> <a href="/atletas">
                <li class="rounded-md hover:bg-slate-200 indent-0.5 w-40 flex float:left items-center"><span class="material-icons-regular text-[19px] text-[#a15959]">face</span> Listar atletas</li>
              </a> <?php endif; ?>

            <?php if (isset($this->user_role) && $this->user_role === 'titular' && $path === '/usuario'): ?>
              <a href="https://axelpatinacao.basedeclientes.com.br" target="_blank" title="Área financeira da Axel">
                <li class="rounded-md hover:bg-slate-200 indent-0.5 w-40 flex float:left items-center"><span class="material-icons-regular text-[19px] text-[#a15959]">Attach_Money</span> Financeiro</li>
              </a>
            <?php endif; ?>
            <?php if ($this->user_role && ($this->user_role === 'admin' || $this->user_role === 'monitor') && $path !== '/nova_turma'): ?> <a href="/nova_turma" title="Criar uma turma nova">
                <li class="rounded-md hover:bg-slate-200 indent-0.5 w-35 flex float:left items-center"><span class="material-icons-regular text-[19px] text-[#a15959]">Manage_Accounts</span>Nova turma</li>
              </a> <?php endif; ?> <?php if ((isset($this->user_role) && ($this->user_role === 'admin' || $this->user_role === 'monitor')) && $path !== '/turmas'): ?> <a href="/turmas">
                <li class="rounded-md hover:bg-slate-200 indent-0.5 w-40 flex float:left items-center"><span class="material-icons-regular text-[19px] text-[#a15959]">Manage_Accounts</span> Listar turmas</li>
              </a> <?php endif; ?> <?php if ((isset($this->user_role) && ($this->user_role !== 'guest' && $this->user_role !== 'usuario' && $this->user_role !== 'titular')) && $path !== '/aulas'): ?> <a href="/aulas">
                <li class="rounded-md hover:bg-slate-200 indent-0.5 w-40 flex float:left items-center"><span class="material-icons-regular text-[19px] text-[#a15959]">Manage_Accounts</span>Listar aulas</li>
              </a> <?php endif; ?> <?php if ($this->user_role && $this->user_role !== 'guest'): ?> <a href="/logout">
                <li class="rounded-md hover:bg-slate-200 indent-0.5 w-40 flex float:left items-center font-semi-bold"><span class="material-icons-regular text-[19px] text-[#a15959]">Door_Open</span> Sair / logout</li>
              </a> <?php endif; ?>
          </ul>
        </nav>
      </label>
    </div>

  </header>

  <main class="grow"> <?= $this->content ?> </main>

  <footer class="bg-gray-300 text-center text-gray-700 max-w-full text-sm mt-10">©2025 Axel Patinação Artística - Todos os direitos reservados.</footer>

  <script>
    document.addEventListener('DOMContentLoaded', () => {
      const container = document.getElementById('containerMenu');
      const checkbox = document.getElementById('botaoMenu');
      let tempoParaFechar;
      if (container && checkbox) {
        // 1. Fechar ao sair do menu com o mouse
        container.addEventListener('mouseleave', () => {
          tempoParaFechar = setTimeout(() => {
            checkbox.checked = false;
          }, 80);
        });
        container.addEventListener('mouseenter', () => {
          clearTimeout(tempoParaFechar);
        });
        // 2. Fechar ao clicar FORA do container
        document.addEventListener('click', (e) => {
          var link = e.target.closest('a');
          if (link) {
            checkbox.checked = false;
          }
          // Se o clique NÃO foi dentro do containerMenu, fecha o checkbox
          if (!container.contains(e.target)) {
            checkbox.checked = false;
          }
        });

      }

    });

    // Seleciona todos os inputs que possuem um datalist associado
    document.querySelectorAll('input[list]').forEach(el => {
      if (page === 'atleta.phtml') { // 'const page = 'atleta.phtml';' está na pag. atleta.phtml
        return;
      };
      // Quando o usuário clica ou foca no campo
      el.addEventListener('focus', function() {
        this.oldValue = this.value; // Salva o valor atual (ex: "iniciante01")
        this.value = ''; // Limpa para o navegador mostrar todas as opções
      });

      // Quando o usuário clica fora do campo
      el.addEventListener('blur', function() {
        // Se ele não escolheu nada novo, devolve o valor original
        if (this.value === '') {
          this.value = this.oldValue;
        }
      });
      // Opcional: "Se ele escolher uma opção da lista, o 'blur' mantém a nova escolha";
    });
  </script>
</body>

</html>